Maubby/Galibelum

- app/Resources/views/base.html.twig
- web/assets/css/style.css
Créate file assets and css .
Modification file base.html.twig.
> init projet

- app/Resources/views/organization/edit.html.twig
- app/Resources/views/organization/new.html.twig
- app/Resources/views/organization/show.html.twig
- src/AppBundle/Entity/Activity.php
- src/AppBundle/Entity/Organization.php
- src/AppBundle/Form/ActivityType.php
- src/AppBundle/Form/OrganizationType.php
Adding asserts type in Activity.php
> Activity #41

- app/Resources/views/accountmanager/edit.html.twig
- app/Resources/views/accountmanager/index.html.twig
- app/Resources/views/accountmanager/new.html.twig
- app/Resources/views/accountmanager/show.html.twig
- app/Resources/views/offer/edit.html.twig
- app/Resources/views/offer/new.html.twig
- src/AppBundle/Controller/AccountManagerController.php
- src/AppBundle/Entity/AccountManager.php
- src/AppBundle/Entity/Offer.php
- src/AppBundle/Form/AccountManagerType.php
- src/AppBundle/Form/OfferType.php
- src/AppBundle/Form/OrganizationType.php
- src/AppBundle/Tests/Controller/AccountManagerControllerTest.php
Creation of the forms for the offer, accountmangager & generation of the CRUD's Account Manager
> Creation of the forms for the offer, accountmangager & generation of the CRUD's Account Manager

- app/Resources/FOSUserBundle/translations/FOSUserBundle.fr.yml
- app/Resources/FOSUserBundle/translations/validators.fr.yml
- app/Resources/FOSUserBundle/views/ChangePassword/change_password.html.twig
- app/Resources/FOSUserBundle/views/ChangePassword/change_password_content.html.twig
- app/Resources/FOSUserBundle/views/Profile/edit.html.twig
- app/Resources/FOSUserBundle/views/Profile/show.html.twig
- app/Resources/FOSUserBundle/views/Registration/confirmed.html.twig
- app/Resources/FOSUserBundle/views/Registration/register.html.twig
- app/Resources/FOSUserBundle/views/Resetting/check_email.html.twig
- app/Resources/FOSUserBundle/views/Resetting/email.txt.twig
- app/Resources/FOSUserBundle/views/Resetting/request.html.twig
- app/Resources/FOSUserBundle/views/Resetting/request_content.html.twig
- app/Resources/FOSUserBundle/views/Resetting/reset.html.twig
- app/Resources/FOSUserBundle/views/Resetting/reset_content.html.twig
- app/Resources/FOSUserBundle/views/Security/login.html.twig
- app/Resources/FOSUserBundle/views/layout.html.twig
- app/Resources/views/default/index.html.twig
- app/config/config.yml
- app/config/services.yml
- src/AppBundle/Entity/User.php
- src/AppBundle/Form/ProfileType.php
- src/AppBundle/Form/RegistrationType.php
Creation de FOSUserBundle. Creation des vues twig pour FOSUserBUndle.
> Sign in #16

- app/Resources/views/base.html.twig
- app/Resources/views/inscription/index.html.twig
- app/Resources/views/organization/new.html.twig
- assets/scss/bootstrap.scss
- assets/scss/font-awesome.scss
- assets/scss/style.scss
- assets/scss/vendor.scss
- src/AppBundle/Controller/InscriptionController.php
- src/AppBundle/Controller/OrganizationController.php
- src/AppBundle/Entity/Organization.php
- webpack.config.js
Able to Merge again dear @Dine16 ,
There are some modification for : 
- Inscription page (Choosing organization or company) : View and Controller,
- Changing DB for organization ($status have to be nullable )
- Changing the Organization Controller for adapt new_organisation View for organization and company,
Best regards,
> Organization company #54

- app/Resources/FOSUserBundle/views/Registration/email.txt.twig
- app/config/config.yml
Dear Scrum Master, 
I created the view of the confirmation mail and updated the config FOSUser. 
The view is only available for the desktop version.
The responsive version is coming soon.
> Fos user #65

- app/Resources/FOSUserBundle/views/Registration/email.txt.twig
- app/Resources/views/inscription/index.html.twig
- composer.json
- composer.lock
Changing text and style for inscription page and email. 
Updating composer.json and composer.lock.
> Changing text and style for inscription page and email.

- app/Resources/FOSUserBundle/views/Registration/register.html.twig
- assets/scss/register.scss
- webpack.config.js
> Stylized the register form

- src/AppBundle/Form/OrganizationType.php
Dear @Dine16 ,
there is The Fixed Codesniffer for Organization Type.
All src/AppBundle directory are check.
Best regards,
> Fixed last codesniffer alert on Organisation Type

- app/Resources/FOSUserBundle/views/Registration/register.html.twig
- app/Resources/views/inscription/index.html.twig
- assets/scss/login.scss
- assets/scss/register.scss
- assets/scss/style.scss
Dear @Dine16 ,
Add css modification for presentation,
> add css modification for presentation

- app/Resources/FOSUserBundle/views/Registration/register.html.twig
- app/Resources/FOSUserBundle/views/Security/login.html.twig
- app/Resources/views/base.html.twig
- app/config/security.yml
- assets/scss/login.scss
- assets/scss/register.scss
- assets/scss/style.scss
- composer.lock
- src/AppBundle/Form/RegistrationType.php
- Fixing register's view.
- Fixing double redirect.
- Adding CSS and so on.
> Fixing register's view and double redirect.

- app/Resources/FOSUserBundle/views/Resetting/check_email.html.twig
- app/Resources/FOSUserBundle/views/Resetting/request.html.twig
- app/Resources/FOSUserBundle/views/Resetting/request_content.html.twig
- app/Resources/FOSUserBundle/views/Resetting/reset.html.twig
- app/Resources/FOSUserBundle/views/Resetting/reset_content.html.twig
- app/Resources/FOSUserBundle/views/Security/login.html.twig
- app/config/security.yml
- Adding CSS on FOSUser routes.
- Adding routes to security.yml.
- To do : check all CSS errors on all FOSUser forms, to add CSS on profile (edit/show) and change password, add CSS on all FOSUser emails, check all views by W3C.
> Adding CSS on FOSUser routes.

- app/Resources/FOSUserBundle/views/Profile/edit.html.twig
- app/Resources/views/base.html.twig
- assets/scss/profile.scss
- composer.lock
Finishing editing css for profile page so users can update/edit their profile.
> Fix css profile

- app/Resources/views/inscription/index.html.twig
- src/AppBundle/EventListener/RedirectAfterRegistrationSubscriber.php
Dear @Dine16 and @GaetanRole ,
So mister Role the Event listener was usefull ^^. So i take the old one and add it.
and i had an other modification for inscription choose page (delete a <br> space).
> change a br space on inscription choose and add event listener

- app/Resources/views/base.html.twig
- app/Resources/views/organization/edit.html.twig
- assets/scss/organization_edit.scss
- src/AppBundle/Form/OrganizationType.php
I did some CSS's modification for the organization_edit !
> CSS's Modification for the organization_edit

- app/Resources/FOSUserBundle/views/Security/login.html.twig
- app/config/config.yml
- app/config/services.yml
- assets/js/login-script.js
- assets/scss/login.scss
- src/AppBundle/EventListener/EmailConfirmationListener.php
- webpack.config.js
- See commits (flemme de remarquer) & npm run dev.
> Addding event listener, fixing confing and adding css.

- app/Resources/views/dashboard/index.html.twig
- app/Resources/views/inscription/index.html.twig
- app/Resources/views/organization/edit.html.twig
- assets/scss/style.scss
- package-lock.json
- src/AppBundle/Controller/OrganizationController.php
> adding modal on the organization_edit

- app/Resources/FOSUserBundle/views/Profile/edit.html.twig
- app/Resources/views/organization/_new_company_content.html.twig
- app/Resources/views/organization/_new_organization_content.html.twig
- assets/scss/profile.scss
- package-lock.json
Modifying CSS for profile_edit page
Passed W3C ok.
> Fix profile edit

- app/Resources/views/organization/_edit_company_content.html.twig
- app/Resources/views/organization/_edit_organization_content.html.twig
- app/Resources/views/organization/_show_company_content.html.twig
- app/Resources/views/organization/_show_organization_content.html.twig
- app/Resources/views/organization/show.html.twig
- assets/scss/organization_inscription.scss
- assets/scss/organization_show.scss
- package-lock.json
- webpack.config.js
1. Creation of the pages organization_show (part eSport's structure & part company).
2. Modification media-quierries for all pages orginazation.
> Show organization

- app/Resources/views/activity/edit.html.twig
- app/Resources/views/activity/new.html.twig
- assets/scss/activity.scss
@Dine16 , 
I updated the block "return to the dashboard".
I added a fontawesome.
W3C checked
> Activity new #29

- app/Resources/views/offer/edit.html.twig
- app/Resources/views/offer/new.html.twig
- assets/scss/offer.scss
Dear @Dine16 and @GaetanRole ,
I change the margin on edit and new offer's page and change some title on edit page.
> Creating offer page #20

- app/Resources/views/organization/index.html.twig
- app/Resources/views/organization/show.html.twig
Modification to acces to the differents shows pages (structure or conpany). I changed the condition inside the block body for the page sho_organization !
> Modification to acces to the differents shows pages

- app/Resources/views/offer/edit.html.twig
- app/Resources/views/offer/index.html.twig
- app/Resources/views/offer/new.html.twig
- assets/js/datepicker.js
- assets/scss/offer.scss
- src/AppBundle/Controller/OfferController.php
- webpack.config.js
Dear @Dine16 and @GaetanRole ,
There is the page for index offers which list all offers by activities : 
- Html Comment are Ok (No errors).
- Hide activity.type when there is no offer into it.
> Offer index #119

- app/Resources/FOSUserBundle/views/Security/login.html.twig
- app/Resources/views/dashboard/index.html.twig
- app/Resources/views/organization/_edit_company_content.html.twig
- app/Resources/views/organization/_edit_organization_content.html.twig
- composer.lock
- package-lock.json
- src/AppBundle/Controller/OrganizationController.php
Dear Scrum master, 
Modal's Insertion in the dashboard to redirect to activiy_index when you click to offer
Modal's creation to deactivate account for a company or structure in edit_organizaton 
Modification the OrganizationController to do deactivate a account.
> Showing the different activities 

- app/Resources/FOSUserBundle/views/Registration/register.html.twig
- app/Resources/views/activity/index.html.twig
- app/Resources/views/base_back.html.twig
- app/Resources/views/manager/index.html.twig
- app/Resources/views/organization/_edit_company_content.html.twig
- app/Resources/views/organization/_edit_organization_content.html.twig
- app/Resources/views/organization/index.html.twig
- assets/scss/admin.scss
- src/AppBundle/Controller/LoginController.php
- src/AppBundle/Controller/ManagerController.php
Creating an account manager based on the admin one. Fixing little bugs: adding text to the pop up when about to delete the account; changing the date format on offer_index; renaming a btn class to prevent calling all buttons; adding the sidebar when displaying organization_index and stylizing the page a tiny bit.
> Creating an account manager based on the admin one.

- app/Resources/views/admin/index.html.twig
- app/Resources/views/admin/manager.html.twig
- app/Resources/views/base_back.html.twig
- assets/scss/manager.scss
- src/AppBundle/Controller/AdminController.php
- webpack.config.js
Creating a page to update account managers' profile from admin account.
> Account manager

- app/Resources/views/activity/index.html.twig
- app/Resources/views/dashboard/index.html.twig
- app/Resources/views/manager/index.html.twig
- assets/js/table-manager.js
- assets/scss/organization_show.scss
- package-lock.json
- package.json
- webpack.config.js
Hi my Dear, 
Link's creation inside the boxes offers & activities,
put a blue color on the text inside the breadcrumb,
delete the margin bottom,
insert the librery datatable for the manager table.
> Manager test

- app/Resources/FOSUserBundle/views/Profile/edit.html.twig
- app/config/security.yml
- assets/scss/profile.scss
- composer.lock
- src/AppBundle/EventListener/PasswordResettingListener.php
> Adding new event listener about resetting password.

- assets/js/table_manager.js
- src/AppBundle/Controller/OrganizationController.php
- src/AppBundle/Controller/SearchController.php
- src/AppBundle/Repository/ActivityRepository.php
Olaaaa @Dine16 , 
I deleted the search for the data table. 
Code sniff sniff for search controller, organization controller and activity repo. 
Thanks
> Codesniffer #163

- assets/js/table_manager.js
I created a placeholder for the search and i deleted the search input for the page search. 
Thanks
> Search Data Table

- app/Resources/views/activity/edit.html.twig
- app/Resources/views/activity/new.html.twig
- app/Resources/views/organization/edit.html.twig
- app/Resources/views/organization/new.html.twig
- app/config/config.yml
- app/config/parameters.yml.dist
> Modif css#163

- app/config/security.yml
Dear ScrumMaster,
Remerber_me!!!!!!!
> add remember me session settings

- app/Resources/views/activity/edit.html.twig
- app/Resources/views/activity/new.html.twig
- app/Resources/views/organization/edit.html.twig
- composer.lock
- package-lock.json
> modification api google

- app/Resources/views/contractualisation/index.html.twig
Gros changement !!
Search for contractualisation
> Added the search table manager

- app/Resources/views/activity/edit.html.twig
> Updated the view

- .gitignore
- app/Resources/views/base.html.twig
- src/AppBundle/Controller/AdminController.php
- src/AppBundle/Controller/DefaultController.php
- src/AppBundle/Entity/User.php
- src/AppBundle/Form/RegistrationType.php
> Revert "Page cgu"

- app/Resources/TwigBundle/views/Exception/error404.html.twig
- assets/scss/page_404.scss
- composer.lock
> responsive page 404

- app/Resources/views/base_back.html.twig
Hey
I added the edit profil for William. 
XOXO
> Added the edit profil for the super admin

- app/Resources/views/activity/show.html.twig
- app/Resources/views/offer/index.html.twig
- assets/scss/activity_show.scss
Hey,
-Creating a pannel with a "add offer" button on activity_show,
- change index offer : add + for create new activity.
> Correct offer index and add 'add offer' in activity show when empty

- app/Resources/views/dashboard/_activity_carousel_dashboard.html.twig
- app/Resources/views/dashboard/_activity_dashboard.html.twig
- assets/scss/dashboard.scss
- composer.lock
Standarzing the dashboard: same height for activity and offer boxes, adding spaces inside the box.
> Standarzing the dashboard

- app/Resources/FOSUserBundle/views/Registration/register.html.twig
- app/Resources/views/admin/new.html.twig
Adding an information for the password
> Adding an information for the password

- app/Resources/views/activity/show.html.twig
Ola, 
I updated the a href PDF with a fontawesome. 
thx
> Added a fontawesome to see the pdf

- app/Resources/views/activity/index.html.twig
- assets/scss/activity.scss
Standarzing the activity list with offer list: making 3 boxes per line instead of 4, changing title font-size for responsive.
> Standarzing the activity list with offer list

- app/Resources/views/activity/edit.html.twig
- assets/scss/activity.scss
- src/AppBundle/Controller/ManagerController.php
- src/AppBundle/Entity/Activity.php
- src/AppBundle/Form/ActivityType.php
Modifying email sentence when organization has been activated.
Making socialLink nullable=true when both creating and editing an activity.
Editing the delete modal for activity on the same model as offer's one.
> Fix activity

- app/Resources/FOSUserBundle/views/Registration/register.html.twig
- app/Resources/views/email/notification.html.twig
- app/Resources/views/manager/index.html.twig
- assets/scss/activity.scss
- assets/scss/admin.scss
- assets/scss/inscription_choose.scss
- assets/scss/organization_show.scss
- src/AppBundle/Controller/ContractController.php
center the text for the registration
Rectification of the size when a user choose a structure or company
bolder on mail
modication of the sidebar and buttons for the admin account
> Info password

- app/Resources/views/email/notification.html.twig
- app/Resources/views/manager/contract.html.twig
- composer.lock
- package-lock.json
- src/AppBundle/Controller/ActivityController.php
- src/AppBundle/Controller/ContractController.php
- src/AppBundle/Controller/ManagerController.php
- src/AppBundle/Controller/OrganizationController.php
- src/AppBundle/Controller/ProfileController.php
Renaming mails sending when status changes.
Changing code so enveloppe favicon only appears when status is validation and payment.
Code sniffer ok.
> Renaming mails sending when status changes

- app/Resources/views/activity/edit.html.twig
- app/Resources/views/offer/edit.html.twig
- app/Resources/views/organization/_edit_company_content.html.twig
- app/Resources/views/organization/_edit_organization_content.html.twig
- assets/scss/activity.scss
- assets/scss/offer.scss
- assets/scss/organization_inscription.scss
Standarzing delete buttons: font-style and buttons' size.
Standarzing breadcrumb and boxing-canvas' size when editing an organization.
> Fix delete button

- src/AppBundle/Entity/User.php
> the regex +33 works

- app/Resources/views/activity/edit.html.twig
- app/Resources/views/activity/index.html.twig
- app/Resources/views/activity/new.html.twig
- app/Resources/views/contractualisation/index.html.twig
- app/Resources/views/offer/edit.html.twig
- app/Resources/views/offer/index.html.twig
- app/Resources/views/offer/new.html.twig
- app/Resources/views/organization/_edit_company_content.html.twig
- app/Resources/views/organization/_edit_organization_content.html.twig
- app/Resources/views/search/index.html.twig
Writing descriptive text for each page.
> Writing descriptive text for each page

- app/Resources/views/activity/edit.html.twig
- app/Resources/views/activity/new.html.twig
- app/Resources/views/activity/show.html.twig
- assets/js/add_collection_widget.js
- src/AppBundle/Controller/ActivityController.php
adding buttom negatif for page new and edit activity
> Fix buttom negatif

- README.md
- app/Resources/views/dashboard/index.html.twig
- app/Resources/views/offer/edit.html.twig
- app/Resources/views/offer/new.html.twig
- assets/js/fees_calculator.js
- assets/scss/activity.scss
- assets/scss/offer.scss
- src/AppBundle/Controller/ActivityController.php
- src/AppBundle/Controller/ContractController.php
- src/AppBundle/Service/ManagementFeesService.php
- webpack.config.js
Olaaaa, 
I created the script jquery for the fees calculator. 
I fixed modal body bug for the account manager.
I added a round for the fees calculator (on database)
I fixed the height of the flash activity new.
+ updates @CJulien1 
Thanks
> Fees calculator + Little bugs

- app/Resources/views/activity/show.html.twig
- app/Resources/views/dashboard/_activity_carousel_dashboard.html.twig
- app/Resources/views/dashboard/_activity_dashboard.html.twig
- app/Resources/views/dashboard/_offer_carousel_dashboard.html.twig
- app/Resources/views/dashboard/_offer_dashboard.html.twig
- package-lock.json
Editing and adding French date format to the dashboard and every related pages.
> Editing and adding French date format

- app/Resources/views/base.html.twig
- assets/scss/style.scss
Yop,
Fixed bug for account manager modal and button,
Bye,
> change account manager button for responsivity

- app/Resources/views/activity/show.html.twig
- app/Resources/views/base.html.twig
- app/Resources/views/contractualisation/index.html.twig
- app/Resources/views/organization/_edit_company_content.html.twig
- app/Resources/views/search/index.html.twig
- assets/scss/contract_show.scss
- package-lock.json
- src/AppBundle/Entity/Offer.php
- src/AppBundle/Form/OfferType.php
- webpack.config.js
> Fixing dev

- app/Resources/views/search/index.html.twig
- assets/scss/search.scss
- src/AppBundle/Controller/SearchController.php
Dear Scrum Master,
There is the new search bar style
Bye
> Chnage search toobal view

- app/Resources/FOSUserBundle/translations/security.fr.xlf
- app/Resources/FOSUserBundle/views/Security/login.html.twig
- app/Resources/views/base_back.html.twig
- app/Resources/views/manager/user.html.twig
- src/AppBundle/Controller/AdminController.php
- src/AppBundle/Controller/ManagerController.php
Hello, 
I created an users list for resend the confirmation mail. 
Thanks
> Users list

- assets/scss/offer.scss
- composer.lock
- src/AppBundle/Controller/OfferController.php
OfferController: changing handling fee when modifying offer amount.
Offer_edit: changing padding for pop up when about to save modifications made on offer.
> Offer: changing handling fee when modifying offer amount.

- app/Resources/views/_nav.html.twig
- app/Resources/views/base.html.twig
- app/Resources/views/base_back.html.twig
- src/AppBundle/Controller/AdminController.php
- src/AppBundle/Controller/ManagerController.php
Olaaa, 
I created an access to the users list for account manager and admin. (before just for admin)
I fixed little bugs on the login and register (when you are already logged in admin and superadmin you can't access to the login and register page ERROR -> bc notifications).
Thanks
> Show users list for account manager and admin / Fixed login and register bugs

- assets/scss/style.scss
Fixed the footer by @Quelqun2k4
> Fixed footer

- app/Resources/FOSUserBundle/translations/security.fr.xlf
- app/Resources/views/search/index.html.twig
Changing text to display offers on search_index.
Changing text when user is not logged in.
> Changing text to display offers on search_index

- app/Resources/views/activity/new.html.twig
Fini pour le datepicker,
J'ai constaté une suppression des class datepicker donc c'est corrigé
> Fix bug on datepicker

- app/Resources/views/activity/new.html.twig
I managed the differents inputs when you have a server error. (Show date / address when Event ...)
and footer @Quelqun2k4 
Thanks
> Fixed little bugs on the activity new input

- app/Resources/views/activity/edit.html.twig
I deleted the upload name bc when error we are seing the tmp.
> Removed upload name

- app/Resources/FOSUserBundle/views/Profile/edit.html.twig
Stylizing the side bar for the edit part account manager
> Stylizing the side bar for the edit part account manager
